name: Auto Label Issues

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            bug: "bug"
            feature: "enhancement"
            docs: "documentation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


